version: 2.0.1.{build}
image: Visual Studio 2017

clone_folder: c:\azure-functions-cli

build_script:
- cmd: build.cmd

artifacts:
- path: deploy\Azure.Functions.*.zip
  name: Release
- path: deployx86\Azure.Functions.*.zip
  name: Release
- path: deployx64\Azure.Functions.*.zip
  name: Release
- path: dist\test\*.html
  name: Test

deploy:
- provider: AzureBlob
  storage_account_name: functionsclibuilds
  storage_access_key:
    secure: Ragovca8PBMRIjRGsY0Q0MCv7pw5sr06pov6ERYQIH+UWq9Jf0ILvSBZlO8o3mCIAKTf+khFKXeLqYAC6NFS0OvZ+n9GvcFVknSW5fmhOg/L8uYvXUXD4zXc9iO9t5Dh
  container: builds
  folder: $(APPVEYOR_BUILD_VERSION)
  artifact: Release
  set_content_type: true